
/* Drop Tables */

DROP TABLE ATTENDANCES CASCADE CONSTRAINTS;
DROP TABLE COMMENTS CASCADE CONSTRAINTS;
DROP TABLE POSTS CASCADE CONSTRAINTS;
DROP TABLE RECRUITS CASCADE CONSTRAINTS;
DROP TABLE CATEGORYS CASCADE CONSTRAINTS;
DROP TABLE MANAGEMENT CASCADE CONSTRAINTS;
DROP TABLE MESSAGES CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE ATTENDANCES
(
	ATT_CODE varchar2(7) NOT NULL,
	U_CODE varchar2(7) NOT NULL,
	ATT_CONTENT varchar2(4000) NOT NULL,
	ATT_DATE date NOT NULL,
	PRIMARY KEY (ATT_CODE)
);


CREATE TABLE CATEGORYS
(
	CATE_CODE varchar2(2) NOT NULL,
	CATE_NAME varchar2(30) NOT NULL UNIQUE,
	PRIMARY KEY (CATE_CODE)
);


CREATE TABLE COMMENTS
(
	CMT_CODE_FST varchar2(8) NOT NULL,
	CMT_CODE_SND varchar2(5) NOT NULL,
	POST_CODE varchar2(8) NOT NULL,
	U_CODE varchar2(7) NOT NULL,
	CMT_CONT varchar2(4000) NOT NULL,
	CMT_DATE date NOT NULL,
	PRIMARY KEY (CMT_CODE_FST, CMT_CODE_SND)
);


CREATE TABLE MANAGEMENT
(
	U_CODE varchar2(7) NOT NULL,
	M_LEVEL char NOT NULL,
	PRIMARY KEY (U_CODE)
);


CREATE TABLE MESSAGES
(
	MSG_CODE varchar2(8) NOT NULL,
	MSG_FROM varchar2(7) NOT NULL,
	MSG_TO varchar2(7) NOT NULL,
	MSG_CONT varchar2(4000) NOT NULL,
	MSG_DATE date NOT NULL,
	MSG_FROM_STATE char NOT NULL,
	MSG_TO_STATE char NOT NULL,
	PRIMARY KEY (MSG_CODE)
);


CREATE TABLE POSTS
(
	POST_CODE varchar2(8) NOT NULL,
	U_CODE varchar2(7) NOT NULL,
	CATE_CODE varchar2(2) NOT NULL,
	POST_TITLE varchar2(120) NOT NULL,
	POST_CONT varchar2(4000) NOT NULL,
	POST_HIT number,
	POST_DATE date,
	POST_GOOD number,
	PRIMARY KEY (POST_CODE)
);


CREATE TABLE RECRUITS
(
	RECU_CODE varchar2(6) NOT NULL,
	U_CODE varchar2(7) NOT NULL,
	CATE_CODE varchar2(2) NOT NULL,
	RECU_TITLE varchar2(120) NOT NULL,
	RECU_CONT varchar2(4000) NOT NULL,
	RECU_DATE date NOT NULL,
	RECU_DEAD varchar2(8) NOT NULL,
	RECU_P_NUM number NOT NULL,
	RECU_P_MAX number NOT NULL,
	RECU_HIT number,
	PRIMARY KEY (RECU_CODE)
);


CREATE TABLE USERS
(
	U_CODE varchar2(7) NOT NULL,
	U_ID varchar2(15) NOT NULL UNIQUE,
	U_PW varchar2(15) NOT NULL,
	U_NICK varchar2(30) NOT NULL,
	U_NAME varchar2(30) NOT NULL,
	U_TEL varchar2(13) NOT NULL,
	U_EMAIL varchar2(30) NOT NULL UNIQUE,
	U_SEX char NOT NULL,
	U_STATE char NOT NULL,
	U_POINT number,
	U_REG_DATE varchar2(8),
	PRIMARY KEY (U_CODE)
);



/* Create Foreign Keys */

ALTER TABLE POSTS
	ADD FOREIGN KEY (CATE_CODE)
	REFERENCES CATEGORYS (CATE_CODE)
;


ALTER TABLE RECRUITS
	ADD FOREIGN KEY (CATE_CODE)
	REFERENCES CATEGORYS (CATE_CODE)
;


ALTER TABLE COMMENTS
	ADD FOREIGN KEY (POST_CODE)
	REFERENCES POSTS (POST_CODE)
;


ALTER TABLE ATTENDANCES
	ADD FOREIGN KEY (U_CODE)
	REFERENCES USERS (U_CODE)
;


ALTER TABLE COMMENTS
	ADD FOREIGN KEY (U_CODE)
	REFERENCES USERS (U_CODE)
;


ALTER TABLE MANAGEMENT
	ADD FOREIGN KEY (U_CODE)
	REFERENCES USERS (U_CODE)
;


ALTER TABLE MESSAGES
	ADD FOREIGN KEY (MSG_TO)
	REFERENCES USERS (U_CODE)
;


ALTER TABLE MESSAGES
	ADD FOREIGN KEY (MSG_FROM)
	REFERENCES USERS (U_CODE)
;


ALTER TABLE POSTS
	ADD FOREIGN KEY (U_CODE)
	REFERENCES USERS (U_CODE)
;


ALTER TABLE RECRUITS
	ADD FOREIGN KEY (U_CODE)
	REFERENCES USERS (U_CODE)
;

SELECT * FROM POSTS;

